# Generated by Django 2.1.2 on 2018-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('one_to_one', 'one to one'), ('one_to_many', 'one to many'), ('flip_classroom', 'flipped classroom'), ('application', 'application')], max_length=20),
        ),
    ]
