# Generated by Django 2.1.2 on 2018-11-13 04:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('feed', '0002_auto_20181112_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subjects_list',
            field=models.CharField(choices=[('Networks', 'Networks'), ('Electronic Devices', 'Electronic Devices'), ('Analog Circuits', 'Analog Circuits'), ('Digital circuits', 'Digital circuits'), ('Signals and Systems', 'Signals and Systems'), ('Control Systems', 'Control Systems'), ('Communications', 'Communications'), ('Electromagnetics', 'Electromagnetics')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('one_to_one', 'one to one'), ('one_to_many', 'one to many'), ('flip_classroom', 'flipped classroom'), ('application', 'application'), ('group study', 'group study')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
