# Generated by Django 2.1.2 on 2018-11-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20181113_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subjects_list',
        ),
    ]
